# Generated by Django 3.0.8 on 2020-08-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(blank=True, choices=[('allcat', 'allcat'), ('mobiles', 'mobiles'), ('tvs', 'tvs'), ('headphones', 'headphones'), ('homeappliences', 'homeappliences'), ('laptops', 'laptops')], max_length=40, null=True),
        ),
    ]
