# Generated by Django 2.2.13 on 2021-05-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('men', 'men'), ('women', 'women')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(blank=True, choices=[('allcat', 'allcat'), ('mobiles', 'mobiles'), ('tvs', 'tvs'), ('headphones', 'headphones'), ('homeappliences', 'homeappliences'), ('laptops', 'laptops'), ('menwear', 'menwear'), ('ornaments', 'ornaments'), ('footwear', 'footwear'), ('shirts', 'shirts'), ('womenwear', 'womenwear'), ('pantsmen', 'pantsmen')], max_length=40, null=True),
        ),
    ]
