# Generated by Django 3.1.4 on 2021-05-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
