# Generated by Django 3.1.4 on 2021-05-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210521_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status2',
            field=models.CharField(choices=[('Order Recieved', 'Order Recieved'), ('preparing', 'preparing'), ('prepared', 'prepared'), ('Out for delivery', 'Out for delivery'), ('delivered', 'delivered')], default='Order Recieved', max_length=100),
        ),
    ]
