# Generated by Django 3.1.4 on 2021-05-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210521_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discounted_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
