# Generated by Django 3.1.4 on 2021-05-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discounted_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
